add OS check to scripts

diff --git a/build_scripts/gen_app b/build_scripts/gen_app
--- a/build_scripts/gen_app
+++ b/build_scripts/gen_app
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# make sure we're on Mac
+ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
+if [ "$ostype" != "Darwin" ] ; then
+    echo "ERROR: OS is not macOS.  gen_app only applicable to macOS"
+    echo "Aborting."
+    exit 1
+fi
+
 # add current git hash to VERSION_STR in const.py, saving backup file
 githash=(`git rev-parse --short HEAD`)
 cp marcam/const.py marcam/const.py.bak
diff --git a/build_scripts/gen_dmg b/build_scripts/gen_dmg
--- a/build_scripts/gen_dmg
+++ b/build_scripts/gen_dmg
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# make sure we're on Mac
+ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
+if [ "$ostype" != "Darwin" ] ; then
+    echo "ERROR: OS is not macOS.  gen_dmg only applicable to macOS"
+    echo "Aborting."
+    exit 1
+fi
+
 # from:
 # https://stackoverflow.com/questions/96882/how-do-i-create-a-nice-looking-dmg-for-mac-os-x-using-command-line-tools
 
diff --git a/build_scripts/gen_winexe b/build_scripts/gen_winexe
--- a/build_scripts/gen_winexe
+++ b/build_scripts/gen_winexe
@@ -1,3 +1,13 @@
+#!/bin/bash
+
+# make sure we're on Windows
+ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
+if [ "$ostype" == "Darwin" -o "$ostype" == "Linux" ] ; then
+    echo "ERROR: OS is not Windows.  gen_winexe only applicable to Windows"
+    echo "Aborting."
+    exit 1
+fi
+
 source virt/Scripts/activate
 
 pyinstaller \
